### PR TITLE
 Refactor OnDisconnect class into separate file

### PR DESCRIPTION
**Pull request by jwngr**
**NOTE:** This PR is branched off of #1, which should be reviewed and merged in first.

---
This change is [Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/2)

### CODE REVIEW

**Review by pkaminski — APPROVED** [review]
I really need to implement https://github.com/Reviewable/Reviewable/issues/253 for this use case...

BTW, I'm approving these on the assumption that this is just pure code movement, since Reviewable doesn't do inter-file diffs when parts get split out.  Sigh...

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/2#-:-LI27vGXB0ZyLOGsKxau:b-n0ltei)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by jwngr** [comment]
These are not just pure code movement as I updated these from functions whose prototypes were being updated to proper classes. Beyond that though, the code is very close and the only major changes are properly updating the places where `this` and other function scope stuff is involved.

**Review by pkaminski — DISMISSED** [review]
Sounds good, merge away.

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/2#-:-LI2GSuT2lgpLizRP_HR:b-9tgchc)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jwngr — COMMENTED** [review]
This needs another look after merging in the changes from `master`. The diff should be mostly the same, although I did update the imports and exports to use ES6.

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/2#-:-LIGSobe0KU4GMyExpw0:b-owcskb)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — APPROVED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/2)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/FireCryptOnDisconnect.js, line 27 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/2#-LIHXzuKEKaYiRKhGkLp:-LIHXzuKEKaYiRKhGkLq:b-qgre8o) ([raw file](https://github.com/pkaminski/firecrypt/blob/14f103374f21f9dc339ccb49ad2e9f279fc622d4/src/FireCryptOnDisconnect.js#L27)):*
> ```JavaScript
> }
> 
> export default FireCryptOnDisconnect;
> ```

FYI, I usually prefer to put the `export default` clause together with the class declaration itself.

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/2)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/FireCryptOnDisconnect.js, line 27 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/2#-LIHXzuKEKaYiRKhGkLp:-LIHdrCi-bPqqmahASNa:bftn3bv) ([raw file](https://github.com/pkaminski/firecrypt/blob/14f103374f21f9dc339ccb49ad2e9f279fc622d4/src/FireCryptOnDisconnect.js#L27)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

FYI, I usually prefer to put the `export default` clause together with the class declaration itself.
</blockquote></details>

Makes sense. I'll update these in a follow-up PR.

**Pull request merged**
