### PR TITLE
Support the latest Firebase SDK versions.

### PR DESCRIPTION
**Pull request by pkaminski**
There are two compromises:

1. I gave up on monkeypatching the SDK and instead went with an explicit
function call to wrap a Database object.  The APIs of the client- and
server-side Firebase SDK have diverged, and the team has stated that it's
their attention to diverge further.  Monkeypatching becomes too brittle
in that scenario, so it's now on library clients to ensure that only a
wrapped instance is used.

2. I still use the "compatibility" variant of the client-side API.  This
will be deprecated and possibly removed in the future, at which point
we'll need to fork this library into server and client variants, but
let's cross that bridge when it's thrust upon us (to mix metaphors).

- - -
This change is [Reviewable](https://reviewable.io/reviews/reviewable/firecrypt/24)

### CODE REVIEW

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/firecrypt/24)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @pkaminski)

___
*[`src/firecrypt.js` line 2 at r1](https://reviewable.io/reviews/reviewable/firecrypt/24#-NAjdnJxBUzGNljEPnJ0:-NAjdnJxBUzGNljEPnJ1:b-p4jmq1) ([raw file](https://github.com/reviewable/firecrypt/blob/fb9911c61580cd7063a43e13daa47e6626f89062/src/firecrypt.js#L2)):*
> ```JavaScript
> if (typeof require !== 'undefined') {
>   if (typeof LRUCache === 'undefined') global.LRUCache = require('serialized-lru-cache');
> ```

Does this package have the exact same API as the previous one?

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/firecrypt/24)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @earlAchromatic)

___
*[`src/firecrypt.js` line 2 at r1](https://reviewable.io/reviews/reviewable/firecrypt/24#-NAjdnJxBUzGNljEPnJ0:-NAkOibQ8zlM87gDQSTv:ba4vrsw) ([raw file](https://github.com/reviewable/firecrypt/blob/fb9911c61580cd7063a43e13daa47e6626f89062/src/firecrypt.js#L2)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Does this package have the exact same API as the previous one?
</blockquote></details>

It does, but good catch nonetheless!  I needed to temporarily change this to work when the package was `yarn link`ed, and forgot to change it back.

**Review by cgiroux86 — COMMENTED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/firecrypt/24#-:-NAjesRbAez5cVwewYor:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

**Review by earlAchromatic — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/firecrypt/24#-:-NAkVvHP3xniCM04Bb6u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
