### PR TITLE
Refactored utils into separate file

### PR DESCRIPTION
**Pull request by jwngr**
This is step one in updating this library. I am moving each separate class (`Snapshot`, `Query`, `OnDisconnect`, etc.) into its own file to make things easier to manage and find. Since a lot of these use common helpers, I moved them into their own `utils.js` file.

I also added the missing `lru-cache` dep, which will be required once this library become Node.js only.

---
This change is [Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)

### CODE REVIEW

**Review by pkaminski — CHANGES_REQUESTED** [review]
Uh, wait -- this library needs to remain isomorphic, not Node.js only!  Though I don't think that argues against making `lru-cache` a proper dep; I'm not sure why it's missing in the first place.

But if you're going to go ahead and split things up into separate modules, you'll need to add a build system to put these back together for a browser-compatible package.

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1#-:-LHycyb9DXN53_2wgTPd:b-5kc5ir)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by jwngr — COMMENTED** [review]
My mistake. I see now in my notes that you intend to keep this library isomorphic. I added a webpack build step and tried to keep it as minimal as possible while still following best practices. I didn't even add a Babel loader or anything like that.  I figure you can set this up how you like at a later time if you want. For now, this is enough to keep me going and still support Node and browser.

> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1#-:-LI1Ce4WEYIKBLaGksGs:bez8bbf)* status: 2 of 10 files reviewed, all discussions resolved (waiting on @pkaminski)

**Comment by pkaminski** [comment]
___
*[README.md, line 63 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI26ZZyEGDjpY7OoK4Y:-LI26ZZyEGDjpY7OoK4Z:b-5hfusx) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/README.md#L63)):*
> ```Markdown
> ```
> 
> To create a non-minified, development build of the library, run the following command:
> ```

I assume this is just for browser use?

**Review by pkaminski — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jwngr)

___
*[README.md, line 58 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI26L5A0ztgDpq8dkVN:-LI26L5A0ztgDpq8dkVO:b-x2n5w3) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/README.md#L58)):*
> ```Markdown
> 
> ```bash
> $ https://github.com/pkaminski/firecrypt
> ```

Missing `git clone`?
___
*[src/utils.js, line 0 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI27W4M59Q_Jy4Ox_I4:-LI27W4M59Q_Jy4Ox_I5:b-7sizdg) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/src/utils.js#L0)):*
This looks like it's all crypto-related functions, so perhaps `crypto.js` or `encryption.js` would be a better name for the module.

**Review by pkaminski — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 4 unresolved discussions (waiting on @jwngr)

___
*[webpack.common.js, line 7 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI29LMn2uqNg14Tal7v:-LI29LMn2uqNg14Tal7w:b-umlwgv) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/webpack.common.js#L7)):*
> ```JavaScript
>   output: {
>     filename: 'index.js',
>     path: path.resolve(__dirname, 'dist')
> ```

Forgot:  need to update `bower.json` to point to the new entrypoint.  Also, it might be best to have the dev and prod builds go into different files, like `firecrypt.js` and `firecrypt.min.js`.  I'll also need to add a release script later to automate releasing, since it's getting more complex now...

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jwngr)

___
*[README.md, line 63 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI26ZZyEGDjpY7OoK4Y:-LI2FX2A2Ojn7XA_ufpH:b-j4ts4z) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/README.md#L63)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I assume this is just for browser use?
</blockquote></details>

Yeah,  I figured it easier to test a non-minified build locally on the browser. If you'd like, I can remove this and we can just use the source map generated with the prod build for debugging.
___
*[webpack.common.js, line 7 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI29LMn2uqNg14Tal7v:-LI2G5_i7v-6rK0n0r74:bdos0jv) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/webpack.common.js#L7)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Forgot:  need to update `bower.json` to point to the new entrypoint.  Also, it might be best to have the dev and prod builds go into different files, like `firecrypt.js` and `firecrypt.min.js`.  I'll also need to add a release script later to automate releasing, since it's getting more complex now...
</blockquote></details>

Updated to point to the minified file. Would you like me to keep the `package.json` entry point as `src/index.js` or would you like me to point it to a `dist` file as well?

Also, regarding the release script, just note that I have the `dist/` directory in the `.gitignore`, so you will have to make sure you build those before releasing.
___
*[src/utils.js, line  at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI27W4M59Q_Jy4Ox_I4:-LI2GbBUE7biAKNIh7Y2:b-hkx0hw) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/src/utils.js#L)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This looks like it's all crypto-related functions, so perhaps `crypto.js` or `encryption.js` would be a better name for the module.
</blockquote></details>

If it's okay with you, I'd prefer to punt on this for a later PR since so many follow-up PRs use this naming. Also, several methods are not encryption-related (e.g. `cleanSpecification`, `throwNotSetUpError`, `refToPath`).

**Review by pkaminski — DISMISSED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[webpack.common.js, line 7 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI29LMn2uqNg14Tal7v:-LI2IT3G3TAL_d0-Us1v:b-pu9geq) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/webpack.common.js#L7)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Updated to point to the minified file. Would you like me to keep the `package.json` entry point as `src/index.js` or would you like me to point it to a `dist` file as well?

Also, regarding the release script, just note that I have the `dist/` directory in the `.gitignore`, so you will have to make sure you build those before releasing.
</blockquote></details>

Ah, that won't work since `bower` just uses the contents of the repo (and I don't want to set up a convoluted "publish the dist to a separate repo" system).  We're gonna need to commit `dist`.

I think `package.json` points to the top-level `index.js`, and that seems fine to me.
___
*[src/utils.js, line  at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI27W4M59Q_Jy4Ox_I4:-LI2Iwlo5HJFLlHXY0rK:bsk7l7d) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/src/utils.js#L)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

If it's okay with you, I'd prefer to punt on this for a later PR since so many follow-up PRs use this naming. Also, several methods are not encryption-related (e.g. `cleanSpecification`, `throwNotSetUpError`, `refToPath`).
</blockquote></details>

OK.  I think all the methods are related, if you take the wider view that the module is not just about the encryption mechanics but also about _what_ to encrypt.

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: 10 of 13 files reviewed, all discussions resolved

___
*[src/utils.js, line  at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI27W4M59Q_Jy4Ox_I4:-LI3_2e450mkjfUChjzq:b-627av2) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/src/utils.js#L)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

OK.  I think all the methods are related, if you take the wider view that the module is not just about the encryption mechanics but also about _what_ to encrypt.
</blockquote></details>

Will do the rename in a future PR.

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: 10 of 13 files reviewed, all discussions resolved

___
*[webpack.common.js, line 7 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI29LMn2uqNg14Tal7v:-LI3_KLT6RE1fbRtTRVv:bb6un1j) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/webpack.common.js#L7)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Ah, that won't work since `bower` just uses the contents of the repo (and I don't want to set up a convoluted "publish the dist to a separate repo" system).  We're gonna need to commit `dist`.

I think `package.json` points to the top-level `index.js`, and that seems fine to me.
</blockquote></details>

Done

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: 10 of 13 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI3_WKq5-qG2VVwj67d:-LI3_WKq5-qG2VVwj67e:bhpakgp) (no related file):*
Looks like I need your LGTM again and then I can merge this (and the other PRs that rely on it) in.

---

**Review by pkaminski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 2 unresolved discussions (waiting on @pkaminski and @jwngr)

___
*[webpack.common.js, line 7 at r2](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI29LMn2uqNg14Tal7v:-LI3k15cAZgqmWNfAu_P:b-i5w074) ([raw file](https://github.com/pkaminski/firecrypt/blob/8361ea9eaadfdf01cc962cac6889a80659bf870b/webpack.common.js#L7)):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Done
</blockquote></details>

On further reflection, the current `dist` build won't work for `bower`.  The problem is that (AFAICT) it bundles all the dependencies into the dist file rather than letting bower pull them directly into the final client build.  This can result in the same library (e.g., Firebase) being included more than once, and in other libraries being over-included since webpack uses the `package.json` dependencies rather than the subsetted dependencies in `bower.json`.

All we really want to do is to concatenate the split-up source files in a single file, in the right order.  I don't know webpack at all so I don't know if it can do that.  I have used `rollup` in the past to [do this](https://github.com/pkaminski/firetruss/blob/master/Gruntfile.js#L40), with special exceptions specified for modules that I didn't want to get pulled in.

As you're starting to discover, it's a lot easier to deal with multi-build-system isomorphic modules when they're in just one file.  :)

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI6LHIF09J2-0W3BvXu:-LI6LHIF09J2-0W3BvXv:bg7ajo4) (no related file):*
Alright, so I believe I have a working solution with Rollup. The build generates a Node (`dist/firecrypt.js`) and browser (`dist/firecrypt.min.js`) version of FireCrypt. The `package.json` points to `dist/firecrypt.js` and `bower.json` points to `dist/firecrypt.min.js`.  External node module are not included in either case. We need `package.json` to point to a dist file since we now use `import` / `export` (to make sure Rollup inlines the correct stuff) which requires being transpiled. I removed the wrapping IIFE in the main FireCrypt file since Rollup now will handle this itself. Let me know if you're happy with this solution or if you'd like to see something else.

---

**Review by pkaminski — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 6 unresolved discussions (waiting on @pkaminski and @jwngr)

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI6LHIF09J2-0W3BvXu:-LI7DQtx1JOw26A4FI_s:bjo74ri) (no related file):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Alright, so I believe I have a working solution with Rollup. The build generates a Node (`dist/firecrypt.js`) and browser (`dist/firecrypt.min.js`) version of FireCrypt. The `package.json` points to `dist/firecrypt.js` and `bower.json` points to `dist/firecrypt.min.js`.  External node module are not included in either case. We need `package.json` to point to a dist file since we now use `import` / `export` (to make sure Rollup inlines the correct stuff) which requires being transpiled. I removed the wrapping IIFE in the main FireCrypt file since Rollup now will handle this itself. Let me know if you're happy with this solution or if you'd like to see something else.
</blockquote></details>

I like the upgrade to modern ES but I think it may break some of the hackier older code -- see comments below.  Also, please generate a non-minimized browser build since those are a lot easier to deal with in dev, and actually even easier to integrate into a final production build (rather than trying to merge in a min build's source maps).

---
___
*[package.json, line 33 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7CNjdAocoD87p63b4:-LI7CNjdAocoD87p63b5:bgwmqbt) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/package.json#L33)):*
> ```JSON
>     "cryptojs-extension": "pkaminski/cryptojs-extension",
>     "firebase": "^2.4.2",
>     "lru-cache": "^4.1.3",
> ```

I think `lru-cache` and `serialized-lru-cache` will conflict, as they both define an `lru-cache` package.  I've standardized on using `serialized-lru-cache` everywhere since it's browser-compatible.
___
*[rollup.browser.js, line 5 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7EHxB5M07vK3n5Cw0:-LI7EHxB5M07vK3n5Cw1:b-yw9pp6) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/rollup.browser.js#L5)):*
> ```JavaScript
> import minify from 'rollup-plugin-minify-es';
> 
> export default {
> ```

I think you're missing `sourceMap` options.
___
*[rollup.browser.js, line 21 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7CANH4q1e_UukPccy:-LI7CANH4q1e_UukPccz:bhpsvhj) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/rollup.browser.js#L21)):*
> ```JavaScript
>     'firebase',
>     'lru-cache',
>     'cryptojs',
> ```

Did you mean `cryptojs-extension`?
___
*[src/firecrypt.js, line 1 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7Cw5I-WC5y54VcivC:-LI7Cw5I-WC5y54VcivD:bc85er8) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/src/firecrypt.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

If you're switching to modern ES then `'use strict'` should be implicit, I think.
___
*[src/firecrypt.js, line 4 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7D3FZ5W8-aebkRHmt:-LI7D3F_59icJY5gNwMT:b-sdxu0g) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/src/firecrypt.js#L4)):*
> ```JavaScript
> 
> if (typeof require !== 'undefined') {
>   if (typeof Firebase === 'undefined') var Firebase = require('firebase');
> ```

Won't adding `var` here declare a local variable rather than setting the global?  Unless you're relying on hoisting, in which case let's not do that in modern ES source.  ;)

**Comment by pkaminski** [comment]
*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI6LHIF09J2-0W3BvXu:-LI7pUT_ElMczSNpok4b:b6nts28) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I like the upgrade to modern ES but I think it may break some of the hackier older code -- see comments below.  Also, please generate a non-minimized browser build since those are a lot easier to deal with in dev, and actually even easier to integrate into a final production build (rather than trying to merge in a min build's source maps).
</blockquote></details>

Additional meta-comment: please consider whether the time put into refactoring this package's structure will pay dividends when you get to the actual Firebase migration part.  Given how rarely this package is updated and how few people touch it, the additional work and long-term complexity may not be worth it.  I'll let you make the call, though.

---

**Review by jwngr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: 4 of 14 files reviewed, 6 unresolved discussions (waiting on @pkaminski and @jwngr)

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI6LHIF09J2-0W3BvXu:-LID2ab93-5-x7h315gT:bavdtqy) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Additional meta-comment: please consider whether the time put into refactoring this package's structure will pay dividends when you get to the actual Firebase migration part.  Given how rarely this package is updated and how few people touch it, the additional work and long-term complexity may not be worth it.  I'll let you make the call, though.
</blockquote></details>

Alright, please take another look and let me know if things are organized as you'd like. I am not sure if you want or need source maps for all the build flavors, but I can easily remove them if that's the case.

---
___
*[package.json, line 33 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7CNjdAocoD87p63b4:-LICwQpoAsPCbDaGiKdU:b-2onnfx) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/package.json#L33)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think `lru-cache` and `serialized-lru-cache` will conflict, as they both define an `lru-cache` package.  I've standardized on using `serialized-lru-cache` everywhere since it's browser-compatible.
</blockquote></details>

`lru-cache` has been removed.
___
*[src/firecrypt.js, line 1 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7Cw5I-WC5y54VcivC:-LICxMuc8i4hvxKG4hPx:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/src/firecrypt.js#L1)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

If you're switching to modern ES then `'use strict'` should be implicit, I think.
</blockquote></details>

Done.
___
*[src/firecrypt.js, line 4 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7D3FZ5W8-aebkRHmt:-LICwxsW-6J8MEuiVyZr:bg03f02) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/src/firecrypt.js#L4)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Won't adding `var` here declare a local variable rather than setting the global?  Unless you're relying on hoisting, in which case let's not do that in modern ES source.  ;)
</blockquote></details>

Rollup didn't like things as they were initially, but I was able to update them to explicitly name `global`.
___
*[rollup.browser.js, line 5 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7EHxB5M07vK3n5Cw0:-LICxgmb1webQAmJWOmy:bkb483z) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/rollup.browser.js#L5)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think you're missing `sourceMap` options.
</blockquote></details>

Whoops, it looks like I accidentally deleted it.
___
*[rollup.browser.js, line 21 at r5](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI7CANH4q1e_UukPccy:-LICwmHR8U-bL4saHIZM:b-896fix) ([raw file](https://github.com/pkaminski/firecrypt/blob/3dd3ae27e4bd7e7d53618f2e5277cd5f2163186b/rollup.browser.js#L21)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Did you mean `cryptojs-extension`?
</blockquote></details>

Done.

**Review by pkaminski — APPROVED** [review]
> Reviewed 14 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pkaminski/firecrypt/1)* status: all files reviewed, 1 unresolved discussion (waiting on @jwngr)

*[a discussion](https://reviewable.io/reviews/pkaminski/firecrypt/1#-LI6LHIF09J2-0W3BvXu:-LIFPN6IDCWTzTdE4IaY:bbr675r) (no related file):*
<details><summary><i>Previously, jwngr (Jacob Wenger) wrote…</i></summary><blockquote>

Alright, please take another look and let me know if things are organized as you'd like. I am not sure if you want or need source maps for all the build flavors, but I can easily remove them if that's the case.
</blockquote></details>

Yep, I think this will work.  Thanks!

---

**Pull request merged**
